CREATE TABLE color
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code  VARCHAR(255)                            NOT NULL,
    label VARCHAR(255)                            NOT NULL,
    hex   VARCHAR(7)                              NOT NULL,
    CONSTRAINT pk_color PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT                                    NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE variant
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       BIGINT,
    color_id         BIGINT,
    image_url        VARCHAR(255),
    rating           DECIMAL,
    qty              INTEGER                                 NOT NULL,
    lifecycle_status VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_variant PRIMARY KEY (id)
);

ALTER TABLE color
    ADD CONSTRAINT uc_color_code UNIQUE (code);

ALTER TABLE product
    ADD CONSTRAINT uc_product_slug UNIQUE (slug);

ALTER TABLE variant
    ADD CONSTRAINT FK_VARIANT_ON_COLOR FOREIGN KEY (color_id) REFERENCES color (id);

ALTER TABLE variant
    ADD CONSTRAINT FK_VARIANT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);